#!/bin/bash

# build and run the executable
if [[ "$1" == "run" ]]; then
    if [[ -z "$2" || "$2" == "--debug" || "$2" == "-d" ]]; then
        ./out/debug/c-codingbat 2>/dev/null || echo "Debug target not found. Run 'mac build' first"
    elif [[ "$2" == "--release" || "$2" == "-r" ]]; then
        ./out/release/c-codingbat 2>/dev/null || echo "Release target not found. Run 'mac build --release' first"
    else
        echo "Invalid option. Use --debug or --release."
        exit 1
    fi
# build the executable
elif [[ "$1" == "build" ]]; then
    if [[ -z "$2" || "$2" == "--debug" || "$2" == "-d" ]]; then
        mkdir -p out/debug

        # main target
        clang \
        -Iinclude \
        $(find src -name "*.c") \
        -o out/debug/c-codingbat

        # test target
        clang \
        -Iinclude \
        -Iextras/unity/src \
        src/core.c \
        $(find tests -name "*.c") \
        extras/unity/src/unity.c \
        -o out/debug/c-codingbat-tests
    elif [[ "$2" == "--release" || "$2" == "-r" ]]; then
        mkdir -p out/release

        # main target
        clang \
        -O3 -march=native \
        -Iinclude \
        $(find src -name "*.c") \
        -o out/release/c-codingbat

        # test target
        clang \
        -O3 -march=native \
        -Iinclude \
        -Iextras/unity/src \
        src/core.c \
        $(find tests -name "*.c") \
        extras/unity/src/unity.c \
        -o out/release/c-codingbat-tests
    elif [[ "$2" == "--all" || "$2" == "-a" ]]; then
        # Build for debug
        ./build build -d

        # Build for release
        ./build build -r
    else
        echo "Invalid option. Use --debug or --release or --all."
        exit 1
    fi
# unittest
elif [[ "$1" == "test" ]]; then
    if [[ -z "$2" || "$2" == "--debug" || "$2" == "-d" ]]; then
        ./out/debug/c-codingbat-tests 2>/dev/null || echo "Debug test target not found. Run 'mac build' first"
    elif [[ "$2" == "--release" || "$2" == "-r" ]]; then
        ./out/release/c-codingbat-tests 2>/dev/null || echo "Release test target not found. Run 'mac build --release' first"
    else
        echo "No test target found!!"
        exit 1;
    fi
# clean the build directory
elif [[ "$1" == "clean" ]]; then
    if [[ "$2" == "--debug" || "$2" == "-d" ]]; then
        rm -rf out/debug
        echo "Cleaned debug build directory."
    elif [[ "$2" == "--release" || "$2" == "-r" ]]; then
        rm -rf out/release
        echo "Cleaned release build directory."
    else
        rm -rf out
        echo "Cleaned all build directories."
    fi
elif [[ "$1" == "help" ]]; then
    glow README.md 2>/dev/null || cat README.md
else
    echo "Usage: ./build [build | run | test | clean | help] [--debug | --release]"
    exit 1
fi
